# qt, deps, core_common
FROM jirofly/oo-qt:5.9.9

ENV TZ=Etc/UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get -y update && \
    apt-get -y install python \
                       python3 \
                       sudo
RUN rm /usr/bin/python && ln -s /usr/bin/python2 /usr/bin/python
ADD . /build_tools
WORKDIR /build_tools

# Define the command to run
RUN cd tools/linux && python3 ./automate.py --platform="linux_arm64"
