name: Build onlyoffice linux/arm64

on: workflow_dispatch


jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: macos-latest 
    steps:
      - name: docker info
        run: |
          sudo systemctl stop docker
          sudo mkdir -p /mnt/lib/docker
          echo '{ "exec-opts": ["native.cgroupdriver=cgroupfs"], "cgroup-parent": "/actions_job","data-root": "/mnt/lib/docker"}' | sudo tee /etc/docker/daemon.json > /dev/null 
          sudo systemctl daemon-reload
          sudo systemctl start docker
    
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # # 配置多平台构建环境
      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     driver-opts: |
      #       image=moby/buildkit:master
      #       network=host

      # Docker Hub 认证
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建并推送镜像（关键配置）
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.onlyoffice.arm
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/oobuild:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
