name: Build onlyoffice linux/arm64

on: workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-24.04-arm
    
    steps:
      - name: docker info
        run: |
          sudo systemctl stop docker
          sudo mkdir -p /mnt/lib/docker
          echo '{ "exec-opts": ["native.cgroupdriver=cgroupfs"], "cgroup-parent": "/actions_job","data-root": "/mnt/lib/docker"}' | sudo tee /etc/docker/daemon.json > /dev/null 
          sudo systemctl daemon-reload
          sudo systemctl start docker
    
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # Docker Hub 认证
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建并推送镜像（关键配置）
      - name: Build and Push
        run: |
          docker build -t jirofly/oobuild:7.1.1.4 -f Dockerfile.onlyoffice.arm .
          docker push jirofly/oobuild:7.1.1.4
