name: Docker Build on macOS
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest  # 指定 macOS 运行环境[3,8](@ref)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # 配置多平台构建工具[2,3](@ref)

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # 使用 Secrets 存储凭证[2,4](@ref)

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.onlyoffice.arm
          platforms: linux/arm64
          push: true
          tags: jirofly/app:latest
