name: Build linux/arm64 macos-13

on: 
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-13
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker on macOS using Colima, Lima-VM, and Homebrew
        uses: douglascamata/setup-docker-macos-action@v1-alpha
        with:
          upgrade-qemu: true

      # Docker Hub 认证
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建并推送镜像（关键配置）
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.onlyoffice.arm
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/oobuild:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
